## **week11_Numpy**

In [3]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.shape

(2, 3)

In [4]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [5]:
a[0]

np.int64(1)

In [6]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

In [7]:
a[:3]

array([10,  2,  3])

In [9]:
b = a[3:]
print(b)
b[0] = 40
print(a)

[40  5  6]
[10  2  3 40  5  6]


In [10]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
a[1, 3]

np.int64(8)

In [12]:
a.ndim

2

In [14]:
print(a.shape)
len(a.shape) == a.ndim

(3, 4)


True

In [16]:
print(a.size)
import math
a.size == math.prod(a.shape)

12


True

In [17]:
a.dtype

dtype('int64')

In [18]:
np.zeros(2)

array([0., 0.])

In [19]:
np.ones(2)

array([1., 1.])

In [21]:
# Create an empty array with 2 elements
np.empty(2) 

array([1., 1.])

In [22]:
np.arange(4)

array([0, 1, 2, 3])

In [23]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [24]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [25]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

In [28]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
print(array_example.ndim)
print(array_example.size)
print(array_example.shape)

3
24
(3, 2, 4)


In [36]:
a = np.arange(6)
print(a)

b = a.reshape(3, 2)
print(b)

np.reshape(a, shape=(1, 6), order='C')

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


array([[0, 1, 2, 3, 4, 5]])

In [39]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)

a2 = a[np.newaxis, :]
print(a2.shape)

row_vector = a[np.newaxis, :]
print(row_vector.shape)

col_vector = a[:, np.newaxis]
print(col_vector.shape)

(6,)
(1, 6)
(1, 6)
(6, 1)


In [40]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)

b = np.expand_dims(a, axis=1)
print(b.shape)

c = np.expand_dims(a, axis=0)
print(c.shape)

(6,)
(6, 1)
(1, 6)


In [42]:
data = np.array([1, 2, 3])

print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

2
[1 2]
[2 3]
[2 3]


In [43]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 5])

[1 2 3 4]


In [44]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [45]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [46]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [47]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [48]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [49]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))


In [50]:
print(a[b])

[1 2 3 4]


In [51]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


In [53]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [54]:
a1 = np.array([[1, 1],
               [2, 2]])
a2 = np.array([[3, 3],
               [4, 4]])

np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [55]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [56]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [57]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [58]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [65]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

b1 = a[0, :]
print(b1)

b1[0] = 99
print(b1)

a

[1 2 3 4]
[99  2  3  4]


array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [68]:
print(data - ones)
print(data * data)
print(data / data)

[0 1]
[1 4]
[1. 1.]


In [69]:
a = np.array([1, 2, 3, 4])

a.sum()

np.int64(10)

In [70]:
b = np.array([[1, 1], [2, 2]])

b.sum(axis=0)

array([3, 3])

In [71]:
b.sum(axis=1)

array([2, 4])

In [72]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [74]:
data = np.array([1, 2, 3])
print(data.max())
print(data.min())
print(data.sum())

3
1
6


In [76]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
print(a.sum())
print(a.min())
print(a.min(axis=0))

4.8595784
0.05093587
[0.12697628 0.05093587 0.26590556 0.5510652 ]


In [77]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [79]:
print(data[0, 1])
print(data[1:3])
print(data[0:2, 0])

2
[[3 4]
 [5 6]]
[1 3]


In [80]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [82]:
data = np.array([[1, 2], [5, 3], [4, 6]])
print(data)
print(data.max(axis=0))
print(data.max(axis=1))

[[1 2]
 [5 3]
 [4 6]]
[5 6]
[2 5 6]


In [83]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [84]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [85]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [87]:
print(np.ones(3))
print(np.zeros(3))

rng = np.random.default_rng()  # the simplest way to generate random numbers
rng.random(3) 

[1. 1. 1.]
[0. 0. 0.]


array([0.01940879, 0.90036943, 0.7266947 ])

In [88]:
print(np.ones((3, 2))) 
print(np.zeros((3, 2))) 
print(rng.random((3, 2))) 

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.99417207 0.72941635]
 [0.68612667 0.22721526]
 [0.82990962 0.89136723]]


In [89]:
rng.integers(5, size=(2, 4)) 

array([[3, 2, 0, 0],
       [0, 1, 1, 4]])

In [91]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [92]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [93]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [94]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [95]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [96]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)
print(indices)
print(occurrence_count)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0 1 2]
[2 1 1]


In [98]:
print(data.reshape(2, 3))
print(data.reshape(3, 2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [99]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [100]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [101]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [102]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_arr = np.flip(arr)
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [103]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [104]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [105]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [106]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [107]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [108]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [109]:
a1 = x.flatten()
a1[0] = 99
print(x)  # Original array
print(a1)  # New array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[99  2  3  4  5  6  7  8  9 10 11 12]


In [110]:
a2 = x.ravel()
a2[0] = 98
print(x)  # Original array
print(a2)  # New array

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[98  2  3  4  5  6  7  8  9 10 11 12]
